# Configuração do banco SQL Server
spring.datasource.url=caminho_banco_de_dados
spring.datasource.username=usuario
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuração do Mailtrap (substitua pelo seu)
spring.mail.host=smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=usuario
spring.mail.password=password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
